import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
			>
				<Toaster
					toastOptions={{
						duration: 7000,
						success: {
							duration: 5000,
						},
						style: {
							backgroundColor: "transparent",
							boxShadow: "none",
							padding: "0",
							width: "auto",
							animation: "fade-in 1s ease-in-out",
						},
						icon: "",
						position: "top-center",
					}}
				/>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
